### PR TITLE
update: style index.html

### PR DESCRIPTION
**Pull request by CooperHash**
make little change of index.html

by the way, as a someone who first open this maybe confused about "comman section" and other section, so if readme can explain it or make a docs will better

### CODE REVIEW

**Comment by a-wing** [comment]
CLA. please. https://github.com/binbat/live777/blob/main/.github/CLA.md#list-of-contributors

**Comment by CooperHash** [comment]
> CLA. please. https://github.com/binbat/live777/blob/main/.github/CLA.md#list-of-contributors

i don't know how to sign cla

**Comment by a-wing** [comment]
Add your name, date in this file bottom

Look like this: (you commit log will confirm you identity) 

```
    Metal A-wing, @a-wing, 2023/10/10
    Yabin Yang, @Marsyew, 2023/10/10
    Wen Yang, @fastfeee, 2023/10/10
    Hongcha Zhang, @hongcha98, 2023/10/10
    Yuanyuan Zhou, @dfasdfasddf, 2023/11/01
```

You best use `git commit --signoff --gpg-sign` use signoff and use PGP verify

If don't have PGP and signoff, Not problem, We accept normal commits

**Comment by CooperHash** [comment]
ok then

**Pull request merged**
