### PR TITLE
cla: add CLA (Contributor License Agreement)

### PR DESCRIPTION
**Pull request by a-wing**
We're need sign  (Contributor License Agreement)

@hongcha98 
@Marsyew 
@fastfeee

### CODE REVIEW

**Comment by a-wing** [comment]
Why @fastfeee don't use own account commit?

**Comment by Marsyew** [comment]
> Why @fastfeee don't use own account commit?

She can't edit the CLA.md

**Comment by a-wing** [comment]
because, she didn’t receive invitation

AC628530-9B6A-4A13-8A1F-C5626D583BE3

**Comment by a-wing** [comment]
On the other hand, she can use PR edit this file

**Pull request merged**
